#! /bin/sh

$HOME/.config/bspwm/scripts/autostart.sh &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           12
bspc config bottom_padding       27

bspc config focused_border_color  '#00FFFF'
bspc config normal_border_color   '#696969'

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Scratchpad sticky=on state=floating hidden=on
bspc rule -a Alacritty:Spotify desktop='^8'
bspc rule -a discord desktop='^9'
bspc rule -a Steam desktop='^10'
bspc rule -a Zathura state=tiled
bspc rule -a zoom desktop='^7' state=floating
bspc rule -a Qalculate-gtk state=floating

#for opengl testing
bspc rule -a 'Hello World' state=floating

alacritty --class Scratchpad,Scratchpad --title Scratchpad &
