vim.opt.backup         = false
vim.opt.breakindent    = true
vim.opt.clipboard      = "unnamedplus"
vim.opt.cmdheight      = 2
vim.opt.completeopt    = { "menu", "menuone", "preview", "noinsert", "noselect" }
vim.opt.conceallevel   = 0
vim.opt.cursorline     = true
vim.opt.expandtab      = true
vim.opt.guifont        = "Fira Code:h17"
vim.opt.hidden         = true
vim.opt.ignorecase     = true
vim.opt.incsearch      = true
vim.opt.linebreak      = true
vim.opt.mouse          = "a"
vim.opt.number         = true
vim.opt.relativenumber = true
vim.opt.shiftwidth     = 4
vim.opt.showmode       = false
vim.opt.signcolumn     = "yes"
vim.opt.smartcase      = true
vim.opt.smartindent    = true
vim.opt.splitbelow     = true
vim.opt.splitright     = true
vim.opt.scrolloff      = 10
vim.opt.sidescrolloff  = 10
vim.opt.swapfile       = false
vim.opt.tabstop        = 4
vim.opt.termguicolors  = true
vim.opt.undofile       = true
vim.opt.updatetime     = 300
vim.opt.writebackup    = false

vim.cmd([[set shortmess+=c]])
vim.cmd([[set formatoptions-=cro]])
vim.cmd("colorscheme onedark")
